import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import mdx from '@astrojs/mdx';

export default defineConfig({
  site: 'https://jskyzero.github.io',
  base: '/ActionGameDesign.ByAI',
  // 保留迁移前的文章地址，静态部署生成跳转页。
  redirects: {
    '/cedec/2009-demons-souls-design/': '/ActionGameDesign.ByAI/fromsoftware/2009-demons-souls-design/',
    '/cedec/2019-sekiro-background-graphics/': '/ActionGameDesign.ByAI/fromsoftware/2019-sekiro-background-graphics/',
    '/cedec/2022-elden-open-world/': '/ActionGameDesign.ByAI/fromsoftware/2022-elden-open-world/',
    '/cedec/2025-elden-background/': '/ActionGameDesign.ByAI/fromsoftware/2025-elden-background/',
    '/gdc/2019-spiderman-ai/': '/ActionGameDesign.ByAI/insomniac-games/2019-spiderman-ai/',
    '/gdc/2019-spiderman-technical-postmortem/': '/ActionGameDesign.ByAI/insomniac-games/2019-spiderman-technical-postmortem/',
    '/gdc/2021-got-lethality/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-lethality/',
    '/gdc/2021-got-melee/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-melee/',
    '/gdc/2021-got-weenies/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-weenies/',
    '/gdc/2021-miles-morales-opening/': '/ActionGameDesign.ByAI/insomniac-games/2021-miles-morales-opening/',
    '/gdc/2021-spiderman-miles-creative-journey/': '/ActionGameDesign.ByAI/insomniac-games/2021-spiderman-miles-creative-journey/',
    '/gdc/2024-spiderman2-procedural-content/': '/ActionGameDesign.ByAI/insomniac-games/2024-spiderman2-procedural-content/',
    '/gdc/2026-got2-combat/': '/ActionGameDesign.ByAI/sucker-punch/2026-got2-combat/',
    '/other/2004-sakurai-risk-reward/': '/ActionGameDesign.ByAI/gdc/2004-sakurai-risk-reward/',
    '/other/2007-game-feel/': '/ActionGameDesign.ByAI/gdc/2007-game-feel/',
    '/other/2009-demons-souls-design/': '/ActionGameDesign.ByAI/fromsoftware/2009-demons-souls-design/',
    '/other/2009-disneyland-level-design/': '/ActionGameDesign.ByAI/gdc/2009-disneyland-level-design/',
    '/other/2009-l4d-ai/': '/ActionGameDesign.ByAI/gdc/2009-l4d-ai/',
    '/other/2010-uncharted-animation-player-control/': '/ActionGameDesign.ByAI/gdc/2010-uncharted-animation-player-control/',
    '/other/2013-fighting-animation-body-mechanics/': '/ActionGameDesign.ByAI/cedec/2013-fighting-animation-body-mechanics/',
    '/other/2014-last-of-us-ellie-buddy-ai/': '/ActionGameDesign.ByAI/gdc/2014-last-of-us-ellie-buddy-ai/',
    '/other/2015-bloodborne/': '/ActionGameDesign.ByAI/gdc/2015-bloodborne/',
    '/other/2017-nioh/': '/ActionGameDesign.ByAI/gdc/2017-nioh/',
    '/other/2017-overwatch-first-person-animation/': '/ActionGameDesign.ByAI/gdc/2017-overwatch-first-person-animation/',
    '/other/2018-celeste-level/': '/ActionGameDesign.ByAI/gdc/2018-celeste-level/',
    '/other/2018-horizon-ai-movement/': '/ActionGameDesign.ByAI/gdc/2018-horizon-ai-movement/',
    '/other/2018-horizon-machine-animation/': '/ActionGameDesign.ByAI/gdc/2018-horizon-machine-animation/',
    '/other/2019-ffxv-ai/': '/ActionGameDesign.ByAI/cedec/2019-ffxv-ai/',
    '/other/2019-sekiro-background-graphics/': '/ActionGameDesign.ByAI/fromsoftware/2019-sekiro-background-graphics/',
    '/other/2019-spiderman-ai/': '/ActionGameDesign.ByAI/insomniac-games/2019-spiderman-ai/',
    '/other/2019-spiderman-technical-postmortem/': '/ActionGameDesign.ByAI/insomniac-games/2019-spiderman-technical-postmortem/',
    '/other/2021-got-lethality/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-lethality/',
    '/other/2021-got-melee/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-melee/',
    '/other/2021-got-weenies/': '/ActionGameDesign.ByAI/sucker-punch/2021-got-weenies/',
    '/other/2021-miles-morales-opening/': '/ActionGameDesign.ByAI/insomniac-games/2021-miles-morales-opening/',
    '/other/2021-spiderman-miles-creative-journey/': '/ActionGameDesign.ByAI/insomniac-games/2021-spiderman-miles-creative-journey/',
    '/other/2022-elden-open-world/': '/ActionGameDesign.ByAI/fromsoftware/2022-elden-open-world/',
    '/other/2023-ff16-combat/': '/ActionGameDesign.ByAI/cedec/2023-ff16-combat/',
    '/other/2024-hifi-rush/': '/ActionGameDesign.ByAI/gdc/2024-hifi-rush/',
    '/other/2024-spiderman2-procedural-content/': '/ActionGameDesign.ByAI/insomniac-games/2024-spiderman2-procedural-content/',
    '/other/2025-astro-bot/': '/ActionGameDesign.ByAI/cedec/2025-astro-bot/',
    '/other/2025-elden-background/': '/ActionGameDesign.ByAI/fromsoftware/2025-elden-background/',
    '/other/2026-got2-combat/': '/ActionGameDesign.ByAI/sucker-punch/2026-got2-combat/',
    '/other/2026-silent-hill-f-melee/': '/ActionGameDesign.ByAI/gdc/2026-silent-hill-f-melee/',
    '/other/2026-tekken-martial/': '/ActionGameDesign.ByAI/cedec/2026-tekken-martial/',
    '/other/level-design-terms/': '/ActionGameDesign.ByAI/cedec/level-design-terms/',
    '/other/tokuda-mhw-design/': '/ActionGameDesign.ByAI/cedec/tokuda-mhw-design/',
  },
  integrations: [mdx()],
  vite: {
    plugins: [tailwindcss()],
  },
});
